version: '3.9'

services:
  dotoapp:
    image: todo_app:1.0
    container_name: todoapp_container
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000